name: Integracion continua

on:
  push:
    branches:  
      - main
      - 'feature/**' 
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configuracion JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache de paquetes de SonarCloud 
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache de paquetes Gradle 
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Dar permisos al wrapper
      run: chmod +x gradlew
    - name: Ejecutar pruebas unitarias
      run: ./gradlew test
    - name: Compilar con Gradle
      run: ./gradlew build    
    - name: Analizar con SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube --info
    - uses: actions/upload-artifact@v2
      with:
        name: CalculadoraTD1-1.0-SNAPSHOT
        path: ./build/libs/CalculadoraTD1-1.0-SNAPSHOT.jar
        
