name: Integracion continua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configuracion JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Dar permisos al wrapper
      run: chmod +x gradlew
    - name: Ejecutar pruebas unitarias
      run: ./gradlew test
    - name: Compilar con Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: CalculadoraTD1-1.0-SNAPSHOT
        path: /build/libs/CalculadoraTD1-1.0-SNAPSHOT.jar
